name: Build Android GKI Image
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-a16-kernel:
    uses: ./.github/workflows/build-kernel-a16.yml
    secrets: inherit
    with:
      debug: false
